version: '3'
services:
  web:
    # Allows us to specify which dockerfile to use to build and from where
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
